[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk

# Option A: Tell the builder script explicitly to link these SDK modules
pico_link_libraries = 
    hardware_flash
    hardware_sync
build_src_flags = -O0 
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
monitor_port = //dev/ttyACM*
# Option B (If Option A doesn't clear it):
build_flags = 
    -Wl,--undefined=flash_range_erase
    -Wl,--undefined=flash_range_program
